### ISSUE TITLE
Detect Exit in VirtualMachine?

### ISSUE THREAD

**Issue by Vinz1911** [azzieg/mindstorms-inventor#4]
Hello 👋 

Your documentation was very helpful. Do you know if it's possible to detect when a program exit's? I rework my bluetooth library for the RI/Spike and want to run some cleanup code when the program stops. 

Thanks and best regards

**Comment by azzieg** [comment]
We now have a reference sheet with decoded blocks (https://github.com/azzieg/mindstorms-inventor/tree/main/word_blocks) and I think you could do something like this by stopping all stacks but yours, doing the cleanup on your stack and exit the program. But I don't think you can interrupt program exit, or at least I don't know how to do it :-)
