### ISSUE TITLE
I'm at lost when trying to test the repo

### ISSUE THREAD

**Issue by NicoKiaru** [azzieg/mindstorms-inventor#7]
Hello, 

This repo looks super nice, but I don't know where to start to try it...

My OS is win 10 and I have a mindstorms Inventor device. I managed to run pybricks and also to run https://github.com/noamraph/mindstorms with pycharm and a conda environment, but this repo looks like it has more functionalities, so I wanted to try it. I flashed back the original rom, but then I'm stuck.

But how can I install and start to run some of the code in the repo ? 

Is there a pip install ?

I cloned the repo and opened it in a conda python 3.8 env in pycharm, but I've got unknown modules everywhere:

![image](https://user-images.githubusercontent.com/20223054/213910075-fb382fcd-821a-4b9c-bade-c85ba62a57fa.png)

I've went through the readme but I couldn't find instructions to start it in practice.

Sorry for the dumb issue, but can you help me figure out where to start ?

Thanks!

**Comment by azzieg** [comment]
The best way to start is to use original Lego Mindstorms Robot Inventor software (https://apps.microsoft.com/store/detail/9MTQ0N7W1D6X for Windows). You can use it to program in Python and upload your programs to the Inventor hub brick. And as explained on the main page, with a little bit of extra initialisation code you can write quite advanced asynchronous code.

Pybricks firmware is fantastic and it also works on other Lego hub bricks, but advanced asynchronous programming is not yet available. It's under development and we're having some discussions on https://github.com/pybricks/support/issues/357.

You can also control Lego hubs over Bluetooth using a variety of open source software, but that's different from running code on the brick itself. Increased latency makes some projects (like self-balancing, line tracking, etc.) more difficult or even impossible, while easier interoperability with other devices and the cloud makes some projects (like remote control or basic IoT projects) easier.

**Comment by azzieg** [comment]
I added https://github.com/azzieg/mindstorms-inventor/blob/main/README.md#expected-setup to clarify the expected setup.

**Comment by NicoKiaru** [comment]
Thank you! It's much clearer to me.
